### ISSUE TITLE
system:auth-delegator role not assigning

### ISSUE THREAD

**Issue by hello2956** [hashicorp/vault-helm#388] opened 2020-09-15 17:28 UTC
**Describe the bug**
deployed the vault-helm chart and observed all the components are deployed properly but the clusterrolebinding which created assigning a cluster role to service account instead of system-authdelegator

**To Reproduce**
version: 0.7.0
installed through argocd
check cluster role binding which created.

  name: vault-agent-injector-binding
  resourceVersion: "39825039"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterrolebindings/vault-agent-injector-binding
  uid: 68c82694-77dd-4834-859a-24c43ee66c07
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: **vault-agent-injector-clusterrole**
subjects:
- kind: ServiceAccount
  name: vault-agent-injector
  namespace: vault

Other useful info to include: vault pod logs, `kubectl describe statefulset vault` and `kubectl get statefulset vault -o yaml` output

**Expected behavior**
the service account  vault-agent-injector should be assigned to system:auth-delegator

**Environment**
EKS 1.17
* vault-helm version: 0.7.0

Chart values:

no customization except external vault address

**Comment by hello2956** [comment] 2020-09-15 17:29
name: vault
version: 0.7.0
dependencies:
  - name: vault
    version: 0.7.0
    repository: https://helm.releases.hashicorp.com

**Comment by jasonodonnell** [comment] 2020-09-15 20:26
Hi @hello2956, the agent injector service account does not require auth-delegator, only the Vault service account needs it (for K8s authentication requests using the K8s auth method).

**Comment by hello2956** [comment] 2020-09-15 20:36
so I can see the helm chart creating a CRB, Role, CFG and SA, do I need to create **vault-auth** service account and a role binding additionally??

**Comment by hello2956** [comment] 2020-09-15 20:40
the values.yaml has an entry for 

# authDelegator enables a cluster role binding to be attached to the service
  # account.  This cluster role binding can be used to setup Kubernetes auth
  # method.  https://www.vaultproject.io/docs/auth/kubernetes.html
  authDelegator:
    enabled: true



I believe this has to provide auth-delegator permissions to the role which created by chart, and user not required to create any external SA. or Rolebindings, we just need to create an entry in vault for vault role, auth path to allow to read secrets

**Comment by jasonodonnell** [comment] 2020-09-15 20:47
Hi @hello2956, let me explain a bit more.

By default Vault Helm installs two services:
* Vault (the Vault server statefulset)
* Vault Agent Injector (the mutating admission webhook that injects Vault Agents into pods).

## Vault Server

The Vault server uses the Token Review API in Kube to authenticate users using the K8s auth method.  We use the system:auth-delegator privileges attached to the Vault service account.  This is automatically done for you during installation:

```
[~] kubectl describe serviceaccount -n vault vault
Name:                vault
Namespace:           vault
Labels:              app.kubernetes.io/instance=vault
                     app.kubernetes.io/managed-by=Helm
                     app.kubernetes.io/name=vault
                     helm.sh/chart=vault-0.7.0
Annotations:         <none>
Image pull secrets:  <none>
Mountable secrets:   vault-token-nf4pk
Tokens:              vault-token-nf4pk
Events:              <none>

[~] kubectl describe clusterrolebinding vault-server-binding -n vault
Name:         vault-server-binding
Labels:       app.kubernetes.io/instance=vault
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=vault
              helm.sh/chart=vault-0.7.0
Annotations:  <none>
Role:
  Kind:  ClusterRole
  Name:  system:auth-delegator
Subjects:
  Kind            Name   Namespace
  ----            ----   ---------
  ServiceAccount  vault  vault
[~] kubectl describe statefulset vault -n vault | grep "Service Account"
  Service Account:  vault
```

## Vault Agent Injector

The Vault Agent Injector requires a ClusterRole service account because it manages pod specs in all Kubernetes namespaces.  You can see that's created by the Helm chart:

```
[~/Git/vault-agent-demo] kubectl describe serviceaccount -n vault vault-agent-injector
Name:                vault-agent-injector
Namespace:           vault
Labels:              app.kubernetes.io/instance=vault
                     app.kubernetes.io/managed-by=Helm
                     app.kubernetes.io/name=vault-agent-injector
Annotations:         <none>
Image pull secrets:  <none>
Mountable secrets:   vault-agent-injector-token-tfhdc
Tokens:              vault-agent-injector-token-tfhdc
Events:              <none>

[~] kubectl describe clusterrole vault-agent-injector-clusterrole
Name:         vault-agent-injector-clusterrole
Labels:       app.kubernetes.io/instance=vault
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=vault-agent-injector
Annotations:  <none>
PolicyRule:
  Resources                                                   Non-Resource URLs  Resource Names  Verbs
  ---------                                                   -----------------  --------------  -----
  mutatingwebhookconfigurations.admissionregistration.k8s.io  []                 []              [get list watch patch]
[~] kubectl describe clusterrolebinding vault-agent-injector-binding
Name:         vault-agent-injector-binding
Labels:       app.kubernetes.io/instance=vault
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=vault-agent-injector
Annotations:  <none>
Role:
  Kind:  ClusterRole
  Name:  vault-agent-injector-clusterrole
Subjects:
  Kind            Name                  Namespace
  ----            ----                  ---------
  ServiceAccount  vault-agent-injector  vault

[~] kubectl describe deployment -n vault vault-agent-injector| grep "Service Account"
  Service Account:  vault-agent-injector
```

**Comment by hello2956** [comment] 2020-09-15 20:53
I am using external vault where I don't see this SA is getting created

"The Vault server uses the Token Review API in Kube to authenticate users using the K8s auth method. We use the system:auth-delegator privileges attached to the Vault service account. This is automatically done for you during installation:"


DO I need to create this separately if I am using a external vault??

**Comment by jasonodonnell** [comment] 2020-09-15 20:57
Aha, I see @hello2956, yes you need to do this separately. My apologies for missing your external use case. We have an issue here https://github.com/hashicorp/vault-helm/issues/376 to automatically make this for you when `externalVaultAddr` is set.  The agent injector SA should only be used by the agent injector.  Hope that helps!

**Comment by jasonodonnell** [comment] 2020-09-15 21:03
Duplicate of #376

**Closed** 2020-09-15 21:03 UTC
