### ISSUE TITLE
Issue launching Vault in HA mode

### ISSUE THREAD

**Issue by danielmittelman** [hashicorp/vault-helm#151] opened 2019-12-18 05:29 UTC
I've used the following configuration to launch a 3-pod Vault deployment on EKS 1.14:
```yaml
server:
  image: 
    tag: 1.3.0
  
  # Run Vault only on dedicated nodes
  tolerations: |
    - key: "dedicated"
      operator: "Equal"
      value: "vault"
      effect: "NoSchedule"
  
  # Run Vault only on dedicated nodes no. 2
  affinity: |
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "asg"
            operator: "In"
            values:
              - "vault"

  ingress:
    enabled: false
  
  dataStorage:
    enabled: false
  
  ha:
    enabled: true
    config: |
      ui = true

      listener "tcp" {
        tls_disable = 1
        address = "127.0.0.1:8200"
        cluster_address = "127.0.0.1:8201"
      }
      
      storage "dynamodb" {
        ha_enabled = "true"
        region = "us-east-1"
        table = "******"
      }

      seal "awskms" {
        region     = "us-east-1"
        kms_key_id = "arn:aws:kms:us-east-1:*********:key/***********"
      }
```

Running commands through the master pod is working, however when I try to run a command from one of the standby pods, it fails and the following message it written to log:
```
2019-12-17T12:56:52.641Z [ERROR] core: error during forwarded RPC request: error="rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp: lookup $(POD_IP): no such host""
```

...

Here's the log output from the **master pod**:
```
==> Vault server configuration:
           AWS KMS KeyID: arn:aws:kms:us-east-1:*****:key/**********
          AWS KMS Region: us-east-1
               Seal Type: awskms
             Api Address: http://$(POD_IP):8200
                     Cgo: disabled
         Cluster Address: https://$(POD_IP):8201
              Listener 1: tcp (addr: "127.0.0.1:8200", cluster address: "127.0.0.1:8201", max_request_duration: "1m30s", max_request_size: "33554432", tls: "disabled")
               Log Level: info
                   Mlock: supported: true, enabled: false
           Recovery Mode: false
                 Storage: dynamodb (HA available)
                 Version: Vault v1.3.0
==> Vault server started! Log data will stream in below:
2019-12-17T12:56:22.977Z [INFO]  proxy environment: http_proxy= https_proxy= no_proxy=
2019-12-17T12:56:23.106Z [INFO]  core: stored unseal keys supported, attempting fetch
2019-12-17T12:56:23.150Z [INFO]  core.cluster-listener: starting listener: listener_address=127.0.0.1:8201
2019-12-17T12:56:23.150Z [INFO]  core.cluster-listener: serving cluster requests: cluster_listen_address=127.0.0.1:8201
2019-12-17T12:56:23.150Z [INFO]  core: entering standby mode
2019-12-17T12:56:23.154Z [INFO]  core: vault is unsealed
2019-12-17T12:56:23.154Z [INFO]  core: unsealed with stored keys: stored_keys_used=1
2019-12-17T12:56:24.156Z [INFO]  core: acquired lock, enabling active operation
2019-12-17T12:56:24.208Z [INFO]  core: post-unseal setup starting
2019-12-17T12:56:24.218Z [INFO]  core: loaded wrapping token key
2019-12-17T12:56:24.218Z [INFO]  core: successfully setup plugin catalog: plugin-directory=
2019-12-17T12:56:24.225Z [INFO]  core: successfully mounted backend: type=system path=sys/
2019-12-17T12:56:24.225Z [INFO]  core: successfully mounted backend: type=identity path=identity/
2019-12-17T12:56:24.225Z [INFO]  core: successfully mounted backend: type=kv path=secret/
2019-12-17T12:56:24.225Z [INFO]  core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2019-12-17T12:56:24.251Z [INFO]  core: successfully enabled credential backend: type=token path=token/
2019-12-17T12:56:24.251Z [INFO]  core: successfully enabled credential backend: type=jwt path=jwt/
2019-12-17T12:56:24.251Z [INFO]  core: restoring leases
2019-12-17T12:56:24.251Z [INFO]  rollback: starting rollback manager
2019-12-17T12:56:24.264Z [INFO]  identity: entities restored
2019-12-17T12:56:24.268Z [INFO]  identity: groups restored
2019-12-17T12:56:24.272Z [INFO]  expiration: lease restore complete
2019-12-17T12:56:24.312Z [INFO]  core: post-unseal setup complete
```

Log output from a **standby pod**:
```
==> Vault server configuration:
           AWS KMS KeyID: arn:aws:kms:us-east-1:*******:key/************
          AWS KMS Region: us-east-1
               Seal Type: awskms
             Api Address: http://$(POD_IP):8200
                     Cgo: disabled
         Cluster Address: https://$(POD_IP):8201
              Listener 1: tcp (addr: "127.0.0.1:8200", cluster address: "127.0.0.1:8201", max_request_duration: "1m30s", max_request_size: "33554432", tls: "disabled")
               Log Level: info
                   Mlock: supported: true, enabled: false
           Recovery Mode: false
                 Storage: dynamodb (HA available)
                 Version: Vault v1.3.0
==> Vault server started! Log data will stream in below:
2019-12-17T12:56:23.058Z [INFO]  proxy environment: http_proxy= https_proxy= no_proxy=
2019-12-17T12:56:23.187Z [INFO]  core: stored unseal keys supported, attempting fetch
2019-12-17T12:56:23.230Z [INFO]  core.cluster-listener: starting listener: listener_address=127.0.0.1:8201
2019-12-17T12:56:23.230Z [INFO]  core.cluster-listener: serving cluster requests: cluster_listen_address=127.0.0.1:8201
2019-12-17T12:56:23.230Z [INFO]  core: entering standby mode
2019-12-17T12:56:23.233Z [INFO]  core: vault is unsealed
2019-12-17T12:56:23.233Z [INFO]  core: unsealed with stored keys: stored_keys_used=1
```

My suspicion is that for some reason the API address and the cluster address are being set to "$(POD_IP)" in the standby pods instead of the actual pod IP. I do have another Vault deployment (using this Helm chart as well) which is working and the log output shows an IP address rather than `$(POD_IP)`.

**Comment by jasonodonnell** [comment] 2019-12-18 15:14
Hello @danielmittelman,

That's definitely what's going on here, but I can't reproduce it on my end.  Can you tell me more about your environment?  Are you running on EKS?

**Comment by tvoran** [comment] 2020-02-06 02:54
Hi @danielmittelman, I haven't been able to reproduce this issue on EKS yet either. Are you still running into it?

One thing I noticed is that the listener config block should be something more like this:

```
      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }
```

i.e. listening on all interfaces (`[::]`) rather than just local traffic (`127.0.0.1`). This way the active vault will be able to receive traffic from a standby vault.

**Comment by zlyun1979** [comment] 2020-02-19 23:29
I had the same issue. Now fixed with below in vault server statefulset yaml:

            - name: VAULT_ADDR
              value: "{{ include "vault.scheme" . }}://127.0.0.1:8200"
            - name: VAULT_CLUSTER_ADDR
              value: "{{ include "vault.scheme" . }}://$(POD_IP):8200"

**Closed** 2020-05-31 17:54 UTC
Labels: bug, injector, waiting for response

**Comment by glentakahashi** [comment] 2020-12-16 01:11
Hmm, we just hit the same issue but were unable to reproduce. It was entirely sporadic and has only happened to us once when the vault nodes were restarted. It also only happened on 2 of the 3 nodes

**Comment by yzhivkov** [comment] 2021-01-31 17:24
It looks like that if the active pod gets restarted another one takes the active mode but the helm chart (or k8s) does not update the label on the newly active pod (vault-active: "true") leaving the k8s service vault-active with no pods.

I looked up the active pod by going over every pod in the cluster `kubectl exec -it vault-0 -n vault vault status` and once I figured out which one is active, I added the label onto the pod. Definitely not the solution you may be looking for but the only workaround that worked for me.

**Comment by laurentiuspurba** [comment] 2021-02-05 20:29
We were getting the same issue, but were not able to reproduce. It seems when the *Active* node was restarted, the Standby node (candidate to be active), does not where to get Node with port 8201 opened.

One other things, our vault pods were restarted with `Last State Reason` was *Error*. I couldn't find what causing this error.

Any help is appreciated.
