### ISSUE TITLE
Can't create a job in `kube-system` after Vault is installed

### ISSUE THREAD

**Issue by bokysan** [hashicorp/vault-helm#158] opened 2019-12-25 10:17 UTC
Hello,

I've just noticed this. We are using this Vault helm chart. It was deployed three times (2 x vault-0.3.0 and 1 x vault-0.2.1).

It seems that vault deploys an admission webhook which stops our cron job from functioning. Cron is deployed in `kube-system` and when creating a job, the following error is observed:

```
kubectl describe job ecr-cred-helper-1577260800                                                                                            

Name:           ecr-cred-helper-1577260800
Namespace:      kube-system
Selector:       controller-uid=8f37f8c7-26ec-11ea-9889-0225ec1f370e
Labels:         controller-uid=8f37f8c7-26ec-11ea-9889-0225ec1f370e
                job-name=ecr-cred-helper-1577260800
Annotations:    <none>
Controlled By:  CronJob/ecr-cred-helper
Parallelism:    1
Completions:    1
Pods Statuses:  0 Running / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           controller-uid=8f37f8c7-26ec-11ea-9889-0225ec1f370e
                    job-name=ecr-cred-helper-1577260800
  Service Account:  ecr-cred-helper
  Containers:
   ecr-cred-helper:
    Image:      boky/alpine-bootstrap-aws:latest
    Port:       <none>
    Host Port:  <none>
    Command:
      /bin/sh
      /job/refresh-login-token.sh
    Environment:
      SECRET_NAME:            ecr-repository-credentials
      AWS_ACCESS_KEY_ID:      <set to the key 'aws-access-key-id' in secret 'aws-credentials'>      Optional: false
      AWS_SECRET_ACCESS_KEY:  <set to the key 'aws-secret-access-key' in secret 'aws-credentials'>  Optional: false
    Mounts:
      /job from job (rw)
  Volumes:
   job:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      ecr-cred-helper
    Optional:  false
Events:
  Type     Reason        Age                    From            Message
  ----     ------        ----                   ----            -------
  Warning  FailedCreate  5m15s (x24 over 117m)  job-controller  Error creating: Internal error occurred: admission webhook "vault.hashicorp.com" denied the request: error with request namespace: cannot inject into system namespaces: kube-system
```

I believe this to be an error, as Vault should not meddle with other services.

**Comment by jasonodonnell** [comment] 2019-12-26 04:02
@bokysan, I definitely agree this needs to be fixed so I'll prioritize this.

**Comment by jasonodonnell** [comment] 2020-01-02 17:34
This has been fixed in `vault-k8s:0.1.1`, please update your injector deployment.

**Closed by jasonodonnell** 2020-01-02 17:34 UTC

**Comment by derekyle** [comment] 2020-02-06 01:22
Could anyone give some more insight into what is actually causing this problem or a manual fix? Would love to deploy the new update. Unfortunately if your helm tiller pod is not deployed or gets restarted, you can't use helm to update as this bug prevents helm tiller from re-launching.

**Comment by jasonodonnell** [comment] 2020-02-06 01:29
Hi @derekyle, this is being caused by the mutating webhook for the agent injector.  1.0 had a bug where it blocked new pods from being created in `kube-system`.

You can delete it manually to fix this:

```bash
[~/] kubectl get mutatingwebhookconfigurations | grep agent-injector
vault-agent-injector-cfg                             2020-02-06T01:26:45Z
[~/] kubectl delete mutatingwebhookconfigurations vault-agent-injector-cfg
```

Hope that helps!

**Comment by jasonodonnell** [comment] 2020-02-06 01:31
More info on the bug if you're curious: https://github.com/hashicorp/vault-k8s/pull/24

**Comment by derekyle** [comment] 2020-02-06 04:47
Thanks so much! That probably saved me a few hours of learning about "mutatingwebhookconfigurations" that I didn't have the time for at the moment.
