### ISSUE TITLE
Unable to set pod annotations when using dev mode

### ISSUE THREAD

**Issue by yafernandes** [hashicorp/vault-helm#301] opened 2020-05-16 12:38 UTC
I need to setup pod annotations in my dev environment and by the line below the template is ignoring pod annotations if in dev mode.

https://github.com/hashicorp/vault-helm/blob/ac6089c45ef66d4e1eed0e279364ccbb2f8a6eda/templates/_helpers.tpl#L265

**Comment by KadenLNelson** [comment] 2020-08-14 16:18
this is a duplicate of https://github.com/hashicorp/vault-helm/issues/241

**Comment by tvoran** [comment] 2020-08-20 23:15
Fixed in #371

**Closed by tvoran** 2020-08-20 23:15 UTC
