### ISSUE TITLE
Question: Why must mode not equal dev in order to use annotations?

### ISSUE THREAD

**Issue by jason-riddle** [hashicorp/vault-helm#241] opened 2020-03-26 21:39 UTC
As the subject states, here's the relevant line in `_helpers.tpl`

https://github.com/hashicorp/vault-helm/blob/e97f4a579f1bf44cc66d8295573bb01b7d1ff61f/templates/_helpers.tpl#L268-L273

**Comment by jasonodonnell** [comment] 2020-04-13 21:07
Hi @jason-riddle, in the beginning there were some arbitrary restrictions around dev mode but we've tried to remove most of them overtime.  We can remove this restriction since it could be helpful to test a dev server with annotations (for things like istio).

**Comment by KadenLNelson** [comment] 2020-08-14 16:20
Was there a regression? I see in the CHANGELOG that allegedly this restriction was removed in the past as a part of the 0.2.0 release ( October 29th, 2019 ) 🤔

https://github.com/hashicorp/vault-helm/blame/master/CHANGELOG.md#L134

**Comment by jasonodonnell** [comment] 2020-08-20 23:11
I think the CHANGELOG is just wrong. We removed a bunch of these and missed annotations.  This will be fixed in the next release (tomorrow).

**Closed by jasonodonnell** 2020-08-20 23:11 UTC
Labels: chart, question
